### ISSUE TITLE
Update environment rather than stack yaml

### ISSUE THREAD

**Issue by ThatScalaGuy** [lhns/kubedeploy#2]
Instead of modifying the image key via regex in the stack file, another approach could be to use ENV to specify the image:tag in the stack. The service will then update only the ENV and redeploy. The benefit will be that you can update and manage stacks with more than one service. That should work for portainer.

**Comment by lhns** [comment]
That's a really great idea! Would simplify things a lot. I still want to have different types of locators (yaml path for example) but using the ENV would be the easiest for portainer.

**Comment by lhns** [comment]
fixed in v0.2.0

**Comment by ThatScalaGuy** [comment]
Added an environment locator. will create a PR tomorrow.
